### ISSUE TITLE
"Submit Data" dialog won't close or move

### ISSUE THREAD

**Issue by Cady36** [dsiekiera/foe-helfer-extension#1774]
Steps to reproduce:

1. Click the City Overview button.
2. Click Show Submit Button
3. Submit Data
4. Do not close the Submit Data Dialog box
5. Click Show Submit Button
6. Submit Data
7. The new Submit Data dialog box will close (the one with the link to the website).
8. The original Submit Data dialog box is still there, with the link text removed. It will not close when you click the X.
9. Original dialog box requires a refresh to close.

![image](https://user-images.githubusercontent.com/52673062/105190449-dce87100-5aea-11eb-8b7f-15bf330c8a3b.png)

Minor thing, honestly. I had an internet hiccup while submitted, so wasn't sure it submitted, so resubmitted, and the box was stuck on the screen, X didn't work, no text in the box.

(Win 10/Google Chrome.)

**Comment by outoftheline** [comment]
4. Do not close the Submit Data Dialog box

this is the crutial part. i get the same errror.

**Comment by Cady36** [comment]
Since dsiekiera can't reproduce, would a video be helpful? Because I just tried again, and the issue still exists. It's like the dialog box, if it exists when the show Submit Button is clicked, needs to be destroyed. Instead, a new Submit Data DB is added, and the original is stranded. 

Here's a an image of two superimposed. (You get it even if you have not submitted.)

![image](https://user-images.githubusercontent.com/52673062/105611040-ee8a7c80-5d67-11eb-82a8-4d31203a3e77.png)

I checked DevTools and no error is generated.

You can see the duplicate IDs here:

![image](https://user-images.githubusercontent.com/52673062/105611106-3e694380-5d68-11eb-9a6e-324f59ae1f6a.png)

**Comment by vegaz337** [comment]
fixed

**Comment by Cady36** [comment]
Vegaz377, I'm running 2.5.5.1 and I still have this issue. :)

**Comment by danielvoigt01** [comment]
Vegaz377 fixed the issue in his latest pull request. I think the fix is in the next update.

**Comment by Cady36** [comment]
Awesome, thanks. :)

**Comment by vegaz337** [comment]
your welcome, it should work now :)
