### ISSUE TITLE
mopo log

### ISSUE THREAD

**Issue by double816** [dsiekiera/foe-helfer-extension#721]
how do i access and view the mopo log?

**Comment by dsiekiera** [comment]
Register your Player ID (shown in the extension) on the foe-rechner.de website. There are all your Data waiting for u.

**Comment by double816** [comment]
Says……..”oops I couldn’t find anything about this name”I used the 8 digit id from my settings, is that not correct? Sent from Mail for Windows 10 From: Daniel SiekieraSent: Friday, April 3, 2020 11:33 AMTo: dsiekiera/foe-helfer-extensionCc: double816; AuthorSubject: Re: [dsiekiera/foe-helfer-extension] mopo log (#721) Register your Player ID (shown in the extension) on the foe-rechner.de website. There are all your Data waiting for u.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dsiekiera** [comment]
Is fixed now. Pls try again.

**Comment by double816** [comment]
i'm still getting same message.  is there some setting I need to adjust
